# Generated by Django 5.2.1 on 2025-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
