# Generated by Django 5.2.1 on 2025-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_snack_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='image_url',
        ),
        migrations.AddField(
            model_name='snack',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
