# Generated by Django 5.2.1 on 2025-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_snack_image_url_snack_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image_path',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
