# Generated by Django 5.2.1 on 2025-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_snack_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='image_path',
        ),
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snack_images/'),
        ),
    ]
