# Generated by Django 5.2.1 on 2025-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_snack_category_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='category',
            field=models.CharField(choices=[('chips_crisps', 'Chips & Crisps'), ('bars_bites', 'Bars & Bites'), ('popcorn_puffs', 'Popcorn & Puffs'), ('crackers_clusters', 'Crackers & Clusters'), ('dried_fruits', 'Dried Fruits & Slices'), ('roasted_spiced', 'Roasted & Spiced Snacks'), ('cookies_sweets', 'Cookies & Sweets'), ('specialty', 'Specialty Snacks')], default='specialty', max_length=50),
        ),
    ]
